# Generated by Django 4.1.6 on 2023-02-06 08:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_new_category_newsarticle_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
